//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFood.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuisine
    {
        public cuisine()
        {
            this.dishes = new HashSet<dish>();
        }
    
        public int id_cuisine { get; set; }
        public string name_cuisine { get; set; }
    
        public virtual ICollection<dish> dishes { get; set; }
    }
}
