//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFood.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id_review { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public Nullable<int> id_restaurant { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
